CREATE VIEW PAYMENT_WITH_CUSTOMER AS
SELECT PRO.PRODUCT_ID ,PRO.PRODUCT_NAME, PRO.BRAND_NAME, PAY.PAYMENT_ID, PAY.CUSTOMER_ID
FROM PRODUCTS_INFO PRO, PAYMENT_INFO PAY
WHERE PAY.PRODUCT = PRO.PRODUCT_ID;


--INNER JOIN
SELECT CUS.NAME, CUS.PHONE_NUMBER, CUS.ADDRESS, PAY.PAYMENT_ID, PAY.TOTAL_AMOUNT
FROM CUSTOMER_INFO CUS INNER JOIN PAYMENT_INFO PAY
ON CUS.CUSTOMER_ID = PAY.CUSTOMER_ID;


--LEFT OUTER JOIN
SELECT BRAN.BRANCH_ID , EMP.EMPLOYEE_ID, EMP.NAME, EMP.ROLE, BRAN.BRANCH_NAME, BRAN.BRANCH_CONTACT
FROM EMPLOYEE_INFO EMP LEFT OUTER JOIN BRANCH_INFO BRAN
ON EMP.BRANCH_ID = BRAN.BRANCH_ID;



SELECT BRAN.BRANCH_ID , EMP.EMPLOYEE_ID, EMP.NAME, EMP.ROLE, BRAN.BRANCH_NAME, BRAN.BRANCH_CONTACT
FROM EMPLOYEE_INFO EMP INNER JOIN BRANCH_INFO BRAN
ON EMP.BRANCH_ID = BRAN.BRANCH_ID OR EMP.BRANCH_ID < > BRAN.BRANCH_ID;



--RIGHT OUTER JOIN
SELECT PRO.CATEGORY, PRO.PRODUCT_NAME, PRO.STOCK, PAY.PAYMENT_ID, PAY.PAYMENT_DATE
FROM PAYMENT_INFO PAY RIGHT OUTER JOIN PRODUCTS_INFO PRO
ON PAY.PRODUCT = PRO.PRODUCT_ID;


--FULL OUTER JOIN
SELECT MAN.SALESMAN_ID , MAN.NAME, EMP.ROLE, MAN.BRANCH_NAME, MAN.MANAGER_ADDRESS, EMP.PHONE_NUMBER, EMP.BIRTH_OF_DATE, EMP.SALARY
FROM MANAGER_INFO MAN FULL OUTER JOIN EMPLOYEE_INFO EMP
ON MAN.SALESMAN_ID = EMP.EMPLOYEE_ID
ORDER BY ROLE;


--SELF JOIN
SELECT PAY1.CUSTOMER_ID , PAY1.PRODUCT, PAY1.PAYMENT_TYPE, PAY1.TOTAL_AMOUNT,PAY1.PAYMENT_DATE
FROM PAYMENT_INFO PAY1 , PAYMENT_INFO PAY2
WHERE PAY1.CUSTOMER_ID = PAY2.CUSTOMER_ID AND PAY1.PRODUCT <>PAY2.PRODUCT
ORDER BY CUSTOMER_ID;


--NATURAL JOIN/cross join
SELECT PAY.PAYMENT_ID, BRAN.BRANCH_NAME, PAY.PAYMENT_COUNTER, BRAN.BRANCH_CONTACT, BRAN.MANAGER_NAME 
FROM PAYMENT_INFO PAY NATURAL JOIN BRANCH_INFO BRAN
WHERE PAY.BRANCH = BRAN.BRANCH_ID;



