SELECT * FROM CUSTOMER_INFO;

SELECT * FROM PRODUCTS_INFO;

SELECT BRANCH_ID, BRANCH_NAME, BRANCH_CONTACT, ADDRESS FROM BRANCH_INFO;

SELECT EMPLOYEE_ID AS ID_DETAILS , NAME AS NAME FROM EMPLOYEE_INFO;

SELECT PAYMENT_DATE AS THE_DATE FROM PAYMENT_INFO WHERE PAYMENT_COUNTER = 1;

UPDATE PAYMENT_INFO SET PAYMENT_DATE = '12-SEP-22' WHERE PAYMENT_ID = '516162';

SELECT COUNT(STOCK) AS PRODUCT_STOCK_NUM FROM PRODUCTS_INFO WHERE STOCK = 'YES';

SELECT SUM(TOTAL_AMOUNT) AS ONE_DAY_REVENUE FROM PAYMENT_INFO WHERE PAYMENT_DATE = '12-JUN-22';

SELECT MAX(SALARY) AS MAXIMUM_SALARY FROM EMPLOYEE_INFO;

SELECT PAYMENT_COUNTER , SUM(TOTAL_AMOUNT) FROM PAYMENT_INFO GROUP BY PAYMENT_COUNTER;

SELECT PRICE AS OLD_PRICE , PRICE+100 AS NEW_PRICE FROM PRODUCTS_INFO WHERE PRICE > 3000;

SELECT * FROM CUSTOMER_INFO WHERE NAME LIKE 'S%';

SELECT EMPLOYEE_INFO.NAME, SALARY FROM EMPLOYEE_INFO WHERE EMPLOYEE_ID IN ('M001', 'M002');

SELECT PRODUCT_NAME, BRAND_NAME, CATEGORY , PRICE FROM PRODUCTS_INFO ORDER BY PRICE;

SELECT DISTINCT(CATEGORY) FROM PRODUCTS_INFO;