--tuple varaiable

SELECT PRODUCT_ID AS PRODUCTS_CODE , A.PRODUCT_NAME, A.STOCK_COUNT-1 AS STOCK_AFTER_SELL, B.PAYMENT_DATE
FROM PRODUCTS_INFO A, PAYMENT_INFO B
WHERE B.PRODUCT = A.PRODUCT_ID AND STOCK = 'YES'


SELECT NAME AS BUYES_NAME, A.ADDRESS, C.PRODUCT_NAME, B.PAYMENT_ID, B.TOTAL_AMOUNT
FROM CUSTOMER_INFO A, PAYMENT_INFO B ,PRODUCTS_INFO C
WHERE B.PRODUCT = C.PRODUCT_ID AND A.CUSTOMER_ID = B.CUSTOMER_ID


--subqurry


SELECT EMPLOYEE_ID, EMPLOYEE_INFO.NAME, EMPLOYEE_INFO.ROLE
FROM EMPLOYEE_INFO
WHERE EMPLOYEE_ID IN 
(SELECT BRANCH_INFO.MANAGER_ID
FROM BRANCH_INFO
WHERE NUMBER_OF_EMPLOYEE > 10);


--view code

CREATE VIEW CUSTOMER_VIEW_1 AS 
SELECT PRODUCT_ID, PRODUCT_NAME, PRICE 
FROM PRODUCTS_INFO 
WHERE PRODUCT_NAME IS NOT NULL;

CREATE VIEW CUSTOMER_VIEW_2 AS 
SELECT PRODUCT_ID, BRAND_NAME, STOCK
FROM PRODUCTS_INFO 
WHERE BRAND_NAME IS NOT NULL;


CREATE VIEW CUSTOMER_VIEW_3 AS 
SELECT NAME, EMPLOYEE_ID, SALARY
FROM EMPLOYEE_INFO 
WHERE SALARY =  25000;


CREATE VIEW CUSTOMER_VIEW_4 AS 
SELECT PAYMENT_ID, CUSTOMER_ID, PRODUCT, TOTAL_AMOUNT
FROM PAYMENT_INFO; 

SELECT * FROM CUSTOMER_VIEW_1 ;
SELECT * FROM CUSTOMER_VIEW_2 ;
SELECT * FROM CUSTOMER_VIEW_3 ;
SELECT * FROM CUSTOMER_VIEW_4 ;





